name: Test core.py
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  setup-pypy:
    name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        pypy:
        - 'pypy-3.6'
        - 'pypy-3.7'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-python ${{ matrix.pypy }}
        uses: ./
        with:
          python-version: ${{ matrix.pypy }}

      - name: PyPy and Python version
        run: python --version

      - name: Install requirements
        run: cd src && pip3 install -r requirements.txt

      - name: Run code
        run: cd src && python df_import
